<?php
/**
 * @license GPL-2.0-or-later
 *
 * @file
 */

namespace MediaWiki\Extension\RobloxAPI\Args\Types;

/**
 * Represents a return policy argument.
 */
class ReturnPolicyArgument extends ChoiceArgument {

	public function __construct() {
		parent::__construct(
			'return-policy',
			[ 'PlaceHolder', 'ForcePlaceHolder', 'AutoGenerated', 'ForceAutoGenerated' ],
		);
	}

}
