name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch: {}

jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - mw: 'REL1_43'
            php: 8.2
            experimental: false
            coverage: false
            phan: false
          - mw: 'REL1_43'
            php: 8.3
            experimental: false
            coverage: false
            phan: true
          - mw: 'REL1_44'
            php: 8.2
            experimental: false
            coverage: false
            phan: false
          - mw: 'REL1_44'
            php: 8.3
            experimental: false
            coverage: false
            phan: true
          - mw: 'REL1_45'
            php: 8.2
            experimental: false
            coverage: false
            phan: false
          - mw: 'REL1_45'
            php: 8.3
            experimental: false
            coverage: false
            phan: true
          - mw: 'REL1_46'
            php: 8.3
            experimental: false
            coverage: true
            phan: false
          - mw: 'REL1_46'
            php: 8.5
            experimental: false
            coverage: false
            phan: true
            generate_phpunit_config: true
          - mw: 'master'
            php: 8.3
            experimental: true
            coverage: false
            phan: false
            generate_phpunit_config: true
          - mw: 'master'
            php: 8.5
            experimental: true
            coverage: false
            phan: true
            generate_phpunit_config: true

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v6
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}-v2

      - name: Cache Composer cache
        uses: actions/cache@v6
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - uses: actions/checkout@v7
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        run: rm -rf mediawiki && bash EarlyCopy/.github/workflows/installWiki.sh ${{ matrix.mw }}

      - uses: actions/checkout@v7
        with:
          path: mediawiki/extensions/RobloxAPI

      - name: Composer update (core)
        run: composer update
        working-directory: mediawiki

      - name: Set up PHPUnit for coverage generation
        run: |
          php tests/phpunit/generatePHPUnitConfig.php &&
          curl -L \
            -o phpunit-suite-edit.py \
            https://raw.githubusercontent.com/wikimedia/integration-config/04997edbb1f93953575c1d4025b6456e7913d8e8/dockerfiles/quibble-coverage/phpunit-suite-edit.py &&
          python3 phpunit-suite-edit.py phpunit.xml --cover-extension "extensions/RobloxAPI"
        # Only works on MW 1.46+
        if: matrix.coverage == true || matrix.generate_phpunit_config
        working-directory: mediawiki

      - name: Run PHPUnit without coverage
        run: composer run phpunit extensions/RobloxAPI/tests
        if: matrix.coverage == false
        working-directory: mediawiki

      - name: Run PHPUnit and generate coverage report
        run: |
          vendor/bin/phpunit \
            --testsuite extensions \
            --exclude-group Broken \
            --coverage-clover coverage.xml
        if: matrix.coverage == true
        working-directory: mediawiki

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.coverage == true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run parser tests
        run: php tests/parser/parserTests.php --file=extensions/RobloxAPI/tests/parser/parserTests.txt
        working-directory: mediawiki

      - name: Composer update (extension)
        run: composer update
        working-directory: mediawiki/extensions/RobloxAPI
        if: matrix.phan

      - name: Run phan
        working-directory: mediawiki/extensions/RobloxAPI
        run: composer run phan
        if: matrix.phan
  # We only want to run this during full CI for now; in the future, this will be moved to lint-check.yml
  banana-lint:
    name: "Lint message files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm ci
        name: Install dependencies
      - run: npm test
        name: Run banana
